### ISSUE TITLE
Main network overfitting when hp-net trains from scratch

### ISSUE THREAD

**Issue by waitwaitforget** [peiwang062/towards-realistic-predictors#1]
Hi, there,
It's an interesting work and I've tried to reproduce your method on some datasets such as cifar-100. However, if the hp-net trains from scratch, the main network will overfitting and the distribution of the hardness score doesn't look like in your paper. Nearly all of the hardness scores follows a Gaussian distribution with mean at 0.1, but no hard example obviously.

**Comment by Sarah018** [comment]
I only played around mnist and mit, the distribution is fine. Cifar I'm not sure. Probably depends on training setup.

**Comment by waitwaitforget** [comment]
Thanks, I agree with that, maybe for the simple dataset, large networks don't work for such a setting.
